### PR TITLE
hydration with client provider not working as expected need to ignore

### PR DESCRIPTION
**Pull request by enyelsequeira**
# Issues

- When running the template, there are some styles not being processed correctly, and when the `document` is first won't display styles, if you `@ts-ignore` it works fine and styles are there

### CODE REVIEW

**Comment by rtivital** [comment]
Template works correctly with fresh dependencies install, make sure that you are using yarn to install dependencies

**Comment by enyelsequeira** [comment]
@rtivital kindly check the latest commit, you can see that I am running yarn, and when you change to this the layout works correctly however the TS compiler will complain

```js
hydrateRoot(
  <ClientProvider>
    <RemixBrowser />
  </ClientProvider>,
    document,
);
```
the above displays correct UI
image


- Now when you have it the other way around, you can see that the layout gets messed up
```jsx
hydrateRoot(
  document,
  <ClientProvider>
    <RemixBrowser />
  </ClientProvider>,

);

```
image

**Comment by rtivital** [comment]
In your example, you have incorrect `hydrateRoot` function usage which results in `Error: hydrateRoot(...): Target container is not a DOM element.`. If you use the method provided by the template it will not have any errors unless something modifies head before hydration, for example browser extension.

**Comment by enyelsequeira** [comment]
@rtivital your 100% right, seems like this issue was caused by a browser extension, in this case it was `loom` for video recording. Would be a good idea to mention that some extension might mess with styles of mantine no?  made a comment on the readme about it

**Pull request closed without merging**
